{"urls": ["http://eliot.readthedocs.io", "http://nosuchurl"], "action_status": "started", "timestamp": 1593409453.235275, "task_uuid": "16ceffbf-c28c-4b6f-baad-335d756c1d96", "action_type": "check_links", "task_level": [1]}
{"url": "http://eliot.readthedocs.io", "action_status": "started", "timestamp": 1593409453.2493157, "task_uuid": "16ceffbf-c28c-4b6f-baad-335d756c1d96", "action_type": "download", "task_level": [2, 1]}
{"action_status": "succeeded", "timestamp": 1593409467.1272552, "task_uuid": "16ceffbf-c28c-4b6f-baad-335d756c1d96", "action_type": "download", "task_level": [2, 2]}
{"url": "http://nosuchurl", "action_status": "started", "timestamp": 1593409467.1272552, "task_uuid": "16ceffbf-c28c-4b6f-baad-335d756c1d96", "action_type": "download", "task_level": [3, 1]}
{"errno": null, "exception": "requests.exceptions.ConnectionError", "reason": "HTTPConnectionPool(host='nosuchurl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CD58E21710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))", "action_status": "failed", "timestamp": 1593409469.4921887, "task_uuid": "16ceffbf-c28c-4b6f-baad-335d756c1d96", "action_type": "download", "task_level": [3, 2]}
{"exception": "builtins.ValueError", "reason": "HTTPConnectionPool(host='nosuchurl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CD58E21710>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))", "action_status": "failed", "timestamp": 1593409469.4926898, "task_uuid": "16ceffbf-c28c-4b6f-baad-335d756c1d96", "action_type": "check_links", "task_level": [4]}
